<!--#include file="../Inc/conn.asp"-->
<!--#include file="admin_check.asp"-->
<%
id=LaoYRequest(Trim(request("id")))
If id="" then
	set csss=server.createobject("ADODB.Recordset")
	sqls="select id from "&tbname&"_css order by ID desc"
	csss.open sqls,conn,1,3
	If Not csss.Eof Then 
	do while not (csss.eof or err) 
	Call CreateCss(csss("id"))
	csss.movenext
	loop
	end if
	csss.close :set csss=nothing
else
Call CreateCss(id)
end if
Call CreateCss(0)
Call Info("更新成功!")

Public function CreateCss(cssid)
	set css=server.createobject("adodb.recordset")
	sql="select * from "&tbname&"_Css where id="&cssid
	css.open sql,conn,1,1
	Ccss = ""
	Ccss = Ccss&"@import '"&sitepath&"KindEditor/plugins/code/prettify.css';" & VbCrLf
	Ccss = Ccss&"* html,.mw {width:950px;margin:0 auto;background:#ffffff;}" & VbCrLf
	Ccss = Ccss&"* {word-wrap:break-word;word-break:break-all;}" & VbCrLf
	Ccss = Ccss&"body {position:relative; margin:0; text-align:center;background:"&css("bodybg")&";}" & VbCrLf
	Ccss = Ccss&"body,td,div,form {color:#000; font-family: ""宋体"", Arial, Tahoma,Verdana, Helvetica, sans-serif; font-size:12px;}" & VbCrLf
	Ccss = Ccss&"p,ul,ol,dl,dd,h1,h2,h3,h4,h5,h6,ul,li,img,blockquote,form { margin:0; padding:0; border:0; list-style:none;}" & VbCrLf
	Ccss = Ccss&"h1 {text-align:center;font:bold 20px ""Microsoft Yahei"",sans-serif;margin:10px 0;}" & VbCrLf
	Ccss = Ccss&"h3 {text-align:center;font-weight:normal;font-size:12px;padding-bottom:10px;margin-bottom:10px;border-bottom:1px dashed #ccc;}" & VbCrLf
	Ccss = Ccss&".mwall {width:960px;margin:0 auto;padding:0 0 5px 0;background:#ffffff;height:auto!important; height:750px;min-height:750px;}" & VbCrLf
	Ccss = Ccss&"#ad250 {float:left;margin-right:5px;}" & VbCrLf
	Ccss = Ccss&"#ad468 {height:60px;width:468px;margin:5px auto;}" & VbCrLf
	Ccss = Ccss&".bgf7f7f7 {background:#f7f7f7;padding-left:3px;}" & VbCrLf
	Ccss = Ccss&".borderall {border:1px solid "&css("Color2")&";background:"&css("Color3")&";}" & VbCrLf
	Ccss = Ccss&"#clear {margin:0;padding:0;clear:both;background:#ffffff;}" & VbCrLf
	Ccss = Ccss&".note {font-size:12px;color:#999999; font-style:italic;}" & VbCrLf
	Ccss = Ccss&".adgs {padding-left:50px;}" & VbCrLf
	Ccss = Ccss&".none {display:none;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"a:link,a:visited {color:#000000;text-decoration:none;}" & VbCrLf
	Ccss = Ccss&"a:hover {color:#ff0000;text-decoration:underline;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*顶部*/" & VbCrLf
	Ccss = Ccss&"#toplogin {background:#f7f7f7;margin-bottom:5px;overflow:hidden;text-align:left;padding:3px 0;}" & VbCrLf
	Ccss = Ccss&"#toplogin span {float:right;width:410px;text-align:right;margin:4px;}" & VbCrLf
	Ccss = Ccss&".loginForm{position:relative;font-family:""Arial"",""simsun"";padding-left:5px;}" & VbCrLf
	Ccss = Ccss&".loginForm,.loginSelect{float:left;}" & VbCrLf
	Ccss = Ccss&".loginSelect{position:relative;z-index:10;padding-left:5px;padding-top:1px;}" & VbCrLf
	Ccss = Ccss&"#loginBtn{cursor:pointer;width:51px;height:19px;overflow:hidden;border:none;background: url('Connect_logo_3.png') no-repeat left top #C8EFFF;display:inline-block;_display:inline;_zoom:1;color:#498BAF;padding-top:1px;_padding-top:3px;float:left;_margin-top:1px;margin-right:5px;text-align:center}" & VbCrLf
	Ccss = Ccss&"#loginQq{cursor:pointer;width:96px;height:17px;background: url('Connect_logo_3.png') no-repeat left -45px;display:inline-block;_display:inline;_zoom:1;color:#498BAF;padding-top:1px;float:left;_margin-top:1px;margin-right:5px;text-align:center;text-indent:-9999px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#webhead {width:950px;margin:0px auto;}" & VbCrLf
	Ccss = Ccss&"#webhead #logo {float:left;width:200px;}" & VbCrLf
	Ccss = Ccss&"#webhead #banner {float:left;width:480px;height:60px;margin:0 10px;text-align:center;}" & VbCrLf
	Ccss = Ccss&"#webhead #topright {float:right;width:250px;text-align:left;padding:10px 0 0 0;}" & VbCrLf
	Ccss = Ccss&"	#webhead #topright .textad {margin-top:10px;}" & VbCrLf
	Ccss = Ccss&" #webhead #topright .topright3 li{float:left;width:24.9%;line-height:20px;height:20px;}" & VbCrLf
	Ccss = Ccss&" " & VbCrLf
	Ccss = Ccss&"/*导航*/" & VbCrLf
	Ccss = Ccss&"#webmenu {width:950px;margin:0 auto 4px;height:27px;background: "&css("Color1")&";}" & VbCrLf
	Ccss = Ccss&"#webmenu ul {padding-left:20px;}" & VbCrLf
	Ccss = Ccss&"#webmenu li {float:left;font-size:14px;padding:6px 0;color:"&css("Color4")&";margin-right:5px;position:relative;}" & VbCrLf
	Ccss = Ccss&"#webmenu a:link,#webmenu a:visited {color:"&css("Color4")&";font-weight:bold;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*下拉菜单*/" & VbCrLf
	Ccss = Ccss&"#webmenu li div a:link,#webmenu li div a:visited{ display:block; text-decoration:none; color:"&css("Color10")&"; width:100%; height:24px; line-height:24px; text-align:center;}" & VbCrLf
	Ccss = Ccss&"#webmenu li div a:hover{color:"&css("color4")&"; background:"&css("Color1")&"; text-decoration:none;}" & VbCrLf
	Ccss = Ccss&"#webmenu li div{display:none; position:absolute; top:25px; left:0; width:100px;border: 1px solid "&css("color9")&";border-left: 6px solid "&css("color9")&"; background: "&css("color8")&";}" & VbCrLf
	Ccss = Ccss&"#webmenu li {z-index:9999;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#webcopy {width:950px;margin:10px auto 0 auto;border-top:1px solid "&css("Color2")&";padding-top:10px;background:#ffffff;}" & VbCrLf
	Ccss = Ccss&"#webcopy li {margin:3px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*图片文章调用*/" & VbCrLf
	Ccss = Ccss&".topimg {overflow:auto;} " & VbCrLf
	Ccss = Ccss&".topimg li{float:left;width:145px;line-height:25px;text-align:center;}" & VbCrLf
	Ccss = Ccss&".topimg li span {float:left;width:130px;line-height:23px;height:23px;overflow:hidden}" & VbCrLf
	Ccss = Ccss&".topimg li span a:link,.topimg li span a:visited{color:#ff0000;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*首页*/" & VbCrLf
	Ccss = Ccss&"#ileft {float:left;width:212px;}" & VbCrLf
	Ccss = Ccss&"#icenter {float:left;margin:0 5px;width:514px;}" & VbCrLf
	Ccss = Ccss&"	#ileft1 {float:left;width:252px;}" & VbCrLf
	Ccss = Ccss&"	#icenter1 {float:left;margin-left:6px;width:474px;}" & VbCrLf
	Ccss = Ccss&"#iright {float:right;width:212px;}" & VbCrLf
	Ccss = Ccss&".topnews {margin:0 0 5px 7px;}" & VbCrLf
	Ccss = Ccss&".topnews h4 {font:bold 22px Microsoft Yahei,sans-serif;margin:5px auto;line-height:30px;height:30px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&".topnews h4 a{text-decoration:none;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".notice {background:"&css("Color3")&";height:25px;line-height:25px;text-align:left;padding:0 4px;}" & VbCrLf
	Ccss = Ccss&".notice div {float:left;}" & VbCrLf
	Ccss = Ccss&".notice ul {width:400px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&".notice li {float:left;width:400px;line-height:20px;height:20px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#toplist {float:left;width:470px;margin-top:5px;}" & VbCrLf
	Ccss = Ccss&"#toplist li {text-align:left;font-size:14px;line-height:25px;height:25px;overflow:hidden;padding-left:5px;}" & VbCrLf
	Ccss = Ccss&"#toplist li span {float:right;color:#999999;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".userlist {border:1px solid #E7E3E7;border-top:0;}" & VbCrLf
	Ccss = Ccss&".userlist td {text-align:left;height:22px;}" & VbCrLf
	Ccss = Ccss&".topjx {text-align:left;color:#636563;line-height:23px;}" & VbCrLf
	Ccss = Ccss&"#ilist,#ilist212,#ilist250 {border:1px solid "&css("Color2")&";background: #ffffff;text-align:left;margin-bottom:4px;}" & VbCrLf
	Ccss = Ccss&"#ilist9 {width:512px;border:1px solid "&css("Color2")&";background: #ffffff;text-align:left;margin-bottom:5px;}" & VbCrLf
	Ccss = Ccss&"#ilist h6,#ilist212 h6,#ilist250 h6 {color:"&css("Color4")&";background: "&css("Color1")&";padding:5px;margin:1px;font-size:14px;}" & VbCrLf
	Ccss = Ccss&"#ilist h6 span,#ilist212 h6 span,#ilist250 h6 span{float:right;font-size:12px;color:#cccccc;font-weight:normal}" & VbCrLf
	Ccss = Ccss&"#ilist h6 a,#ilist212 h6 a,#ilist250 h6 a{color:"&css("Color4")&";}" & VbCrLf
	Ccss = Ccss&"#ilist9 ul {width:512px;margin:0px auto;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#ilist212 ul {width:210px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#ilist250 ul {width:250px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#ilist {float:left;width:360px;}" & VbCrLf
	Ccss = Ccss&"#ilist ul {padding:0 4px;}" & VbCrLf
	Ccss = Ccss&"#ilist li {float:left;font-size:12px;width:350px;line-height:22px;height:22px;overflow:hidden;margin-left:1px}" & VbCrLf
	Ccss = Ccss&"#ilist212 li {float:left;font-size:12px;width:207px;line-height:22px;height:22px;overflow:hidden;margin-left:1px}" & VbCrLf
	Ccss = Ccss&"#ilist250 li {float:left;font-size:12px;width:244px;line-height:22px;height:22px;overflow:hidden;margin-left:1px;}" & VbCrLf
	Ccss = Ccss&"#iright .ititle {background:url(title_bg.gif) left top no-repeat;color:#424542;font-size:12px;text-align:left;padding:7px 10px;letter-spacing: 5px;font-weight:bold;}" & VbCrLf
	Ccss = Ccss&"#iright .igslist {border-bottom:1px solid #E7E3E7;text-align:left;padding:5px 0 5px 3px;height:68px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&".igslist a:link,.igslist a:visited {color:#FF6500;}" & VbCrLf
	Ccss = Ccss&".igslist li {color:#00309C;padding:3px;line-height:19px;}" & VbCrLf
	Ccss = Ccss&".iltitle {background:url(title_bg2.gif) no-repeat;color:#424542;padding:7px 15px 8px 15px;text-align:left;letter-spacing: 5px;font-weight:bold;}" & VbCrLf
	Ccss = Ccss&".illist {border:1px solid #E7E3E7;border-top:0;text-align:left;padding:5px 4px;position: relative;}" & VbCrLf
	Ccss = Ccss&"#ilall {float:left;width:240px;border-bottom:1px dashed #E7E3E7;padding:5px}" & VbCrLf
	Ccss = Ccss&".ihits {float:left;width:25px;padding:5px 0;text-align:center;margin:0 5px 5px 0;background:#FFEB7B;color:#CE0000;font-weight:bold;}" & VbCrLf
	Ccss = Ccss&".iltitle_1 {float:left;width:198px;text-align:left;}" & VbCrLf
	Ccss = Ccss&".iltitle_1 li {margin-top:4px;color:#8C8A8C}" & VbCrLf
	Ccss = Ccss&".iltitle_1 a:link,.iltitle_1 a:visited {font-size:14px;color:#00309C;text-decoration:underline;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#ilist li a:link,#ilist212 li a:link,#toplist li a:link,#ilist250 li a:link,#ilist li a:visited,#ilist212 li a:visited,#ilist250 li a:visited,#toplist li a:visited{color:"&css("Color7")&";}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".link {padding:10px 5px;text-align:left;line-height:20px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#nw_right {float:"
	If css("content")="left" then
	Ccss = Ccss&"right"
	else 
	Ccss = Ccss&"left"
	end if
	Ccss = Ccss&";}" & VbCrLf
	Ccss = Ccss&"#web2r {border:1px solid "&css("Color2")&";width:300px;background: "&css("Color3")&";text-align:left;margin-bottom:5px;}" & VbCrLf
	Ccss = Ccss&"#web2r h5 {background: "&css("Color1")&";padding:5px;margin:1px;font-size:14px;color:"&css("Color4")&";}" & VbCrLf
	Ccss = Ccss&"#web2r ul {padding:0 4px;}" & VbCrLf
	Ccss = Ccss&"#list10 li {font-size:12px;height:25px;line-height:25px;border-bottom:1px dashed #ccc;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#nw_left {float:"&css("content")&";}" & VbCrLf
	Ccss = Ccss&"#web2l {width:640px;border:1px solid "&css("Color2")&";margin:0 0px 5px 0;text-align:left;}" & VbCrLf
	Ccss = Ccss&"#web2l h5 span {background:#FF0066;color:#ffffff;padding:3px 5px;font-weight:bold;}" & VbCrLf
	Ccss = Ccss&"#web2l h5 span a:link,#web2l h5 span a:visited {color:#FFFFFF;}" & VbCrLf
	Ccss = Ccss&"#web2l h5 span a:hover {color:#FFFF00;text-decoration:none;}" & VbCrLf
	Ccss = Ccss&"#web2l h6 {background: "&css("Color1")&";padding:5px;margin:1px;font-size:14px;color:"&css("Color4")&";}" & VbCrLf
	Ccss = Ccss&"#web2l h6 a{color:"&css("Color4")&";}" & VbCrLf
	Ccss = Ccss&"#web2l #content {width:625px;font-size:14px;line-height:25px;padding:6px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#content a{color:#00F}" & VbCrLf
	Ccss = Ccss&"#web2l #content p{margin-bottom:1em;}" & VbCrLf
	Ccss = Ccss&"#web2l #content #listul a{text-decoration:underline;}" & VbCrLf
	Ccss = Ccss&"#web2l #content .zhaiyao {margin:3px 20px;padding:5px;border:1px solid #ccc;background:#f7f7f7;}" & VbCrLf
	Ccss = Ccss&"#web2l #copy {margin:5px auto;border-bottom:1px dashed #ccc;width:90%;text-align:right;padding:10px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#web2l #content li {font-size:12px;color:#000000;}" & VbCrLf
	Ccss = Ccss&"#web2l #content #listul li a:link,#web2l #content #listul li a:visited {font-size:14px;color:"&css("Color5")&";font-weight:bold;text-decoration:none;}" & VbCrLf
	Ccss = Ccss&"#web2l #content #listul li a:hover {color:#ff0000;text-decoration:underline;}" & VbCrLf
	Ccss = Ccss&"#web2l #content .box{padding:0 1em; line-height:2em; margin-top:5px;padding-bottom:5px;color:"&css("Color6")&"}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".dh {background:url(dh.gif) 6px 8px no-repeat;padding:7px 20px;margin:1px;text-align:left;font-weight:normal;font-size:12px;}" & VbCrLf
	Ccss = Ccss&".dh span {float:right;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*列表分页*/" & VbCrLf
	Ccss = Ccss&"	#page {width:100%;padding:15px 0;}" & VbCrLf
	Ccss = Ccss&" #pagetop {width:100%;padding:3px 0;}" & VbCrLf
	Ccss = Ccss&"	#pagetop ul,#page ul{margin:0 auto 5px auto; display:table;text-align:center;}" & VbCrLf
	Ccss = Ccss&"	#pagetop li,#page li{float:left;*float:none;line-height:21px;height:21px;margin: 2px;display:inline; zoom:1;}" & VbCrLf
	Ccss = Ccss&"	#pagetop span,#page span{display: block; padding: 2px 5px; background: "&css("Color3")&"; border: 1px solid #CCC; color: #999999; }" & VbCrLf
	Ccss = Ccss&"	#pagetop a,#page a{font-size:12px;display: block; text-decoration: none; margin:0px; color: "&css("Color4")&";padding: 2px 5px 2px 5px;background:"&css("Color1")&";}" & VbCrLf
	Ccss = Ccss&"	#pagetop a:link,#pagetop a:visited,#page a:link,#page a:visited {border: 1px solid #CCCCCC; }" & VbCrLf
	Ccss = Ccss&"	#pagetop a:hover,#page a:hover {background:"&css("Color3")&";color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&"	#pagetop #span1,#page #span1 {background:#FFFFFF;display: block;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".gcontent {padding:5px 5px 0 5px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".plun {padding:5px;border-bottom:1px dashed "&css("Color2")&";}" & VbCrLf
	Ccss = Ccss&".ptitle {margin:3px 0;}" & VbCrLf
	Ccss = Ccss&".pnoi {float:left;width:60px;}" & VbCrLf
	Ccss = Ccss&".pIP {float:left;width:130px;}" & VbCrLf
	Ccss = Ccss&".pname {float:left;width:140px;color:#FF0000;}" & VbCrLf
	Ccss = Ccss&".ptime {float:left;width:100px;}" & VbCrLf
	Ccss = Ccss&".pings{width:95%;line-height:18px;padding:10px;margin-bottom:7px;}" & VbCrLf
	Ccss = Ccss&".repings {margin:0 3px;padding:0 15px}" & VbCrLf
	Ccss = Ccss&".sub{height:20px; width:48px; background:url(input_bg.gif); border:0; padding:2px 0 0; font-size:12px;}" & VbCrLf
	Ccss = Ccss&"#MultiPage{margin:10px 20px;font: 12px Arial, Helvetica, sans-serif; overflow:auto;}" & VbCrLf
	Ccss = Ccss&"#MultiPage a{float:left;display:block;padding:2px 6px;text-decoration: none;border: 1px solid "&css("Color2")&"; background:"&css("Color1")&";color:"&css("Color4")&"}" & VbCrLf
	Ccss = Ccss&"#MultiPage a:hover {background:"&css("Color3")&";color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&"#MultiPage .total {margin:0 2px 0 -1px;font-weight: bold;background:"&css("Color3")&";color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&"#MultiPage .pages {margin:0 1px 0 -1px;font-weight: bold;background:"&css("Color3")&";color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&".num {margin-right:1px}" & VbCrLf
	Ccss = Ccss&".redirect{margin-right:1px;height: 16px !important;height:15px}" & VbCrLf
	Ccss = Ccss&"#MultiPage .curpage{margin-right:1px;font-weight: bold;background:"&css("Color3")&";color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&".pingp {float:right;width:250px;height:200px;margin:3px 1px;text-align:left;overflow: auto;overflow-x:hidden;scrollbar-arrow-color:#E70000;scrollbar-base-color:#EFF7FF;}" & VbCrLf
	Ccss = Ccss&"	.pingp img {cursor:pointer;margin:5px 8px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".rclass {float:left;width:298px;margin:0px auto;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&".rclass li {float:left;font-size:13px;font-weight:bold;width:280px;margin:0 5px;padding:8px 0;border-bottom:1px dashed #ccc;}" & VbCrLf
	Ccss = Ccss&".rclass .yaoclass {float:left;font-size:12px;font-weight:normal;width:130px;padding-left:5px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#sclass {float:left;width:314px;margin-bottom:5px;}" & VbCrLf
	Ccss = Ccss&"#sclass h6 {background: "&css("Color1")&";padding:5px 15px;margin:1px;font-size:14px;}" & VbCrLf
	Ccss = Ccss&"#sclass h6 span {float:right;font-weight:normal;font-size:12px;letter-spacing: normal;}" & VbCrLf
	Ccss = Ccss&"#sclass ul {padding:0 4px;}" & VbCrLf
	Ccss = Ccss&"#sclass li {font-size:12px;height:25px;line-height:25px;border-bottom:1px dashed #ccc;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#sclass li a:link,#sclass li a:visited {color:"&css("Color5")&";}" & VbCrLf
	Ccss = Ccss&"#sclass li a:hover {color:#ff0000;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".tags {font-size:12px;padding:4px;margin:5px 10px;}" & VbCrLf
	Ccss = Ccss&".tags a:link,.tags a:visited{color:#0000FF}" & VbCrLf
	Ccss = Ccss&"/*相关文章*/" & VbCrLf
	Ccss = Ccss&"#marticle {float:left;font-size:12px;}" & VbCrLf
	Ccss = Ccss&"#marticle ul {padding-left:5px;}" & VbCrLf
	Ccss = Ccss&"#marticle li {float:left;width:310px;margin-right:5px;line-height:25px;height:25px;overflow:hidden;border-bottom:1px dashed #cccccc;}" & VbCrLf
	Ccss = Ccss&"/*上下篇*/" & VbCrLf
	Ccss = Ccss&".sxart li{margin:8px 0;font-size:14px;color:#ff0000;}" & VbCrLf
	Ccss = Ccss&"/*评论框*/" & VbCrLf
	Ccss = Ccss&".artpl {float:left;}" & VbCrLf
	Ccss = Ccss&".artpl li {margin:6px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"a.photo1 { position: relative; z-index: 0;}" & VbCrLf
	Ccss = Ccss&"a.photo1 span{ position: absolute; left: -999em; visibility: hidden; }" & VbCrLf
	Ccss = Ccss&"a.photo1 span img{background: #fff;color:#f60; padding: 4px; border: solid 1px #ddd;filter:alpha(Opacity=100),-moz-opacity:1,opacity: 1;}" & VbCrLf
	Ccss = Ccss&"a.photo1:hover span{ visibility: visible;top: -100px;left: "
	If css("content")="left" then 
	Ccss = Ccss&"-300"
	else
	Ccss = Ccss&"100" 
	end if
	Ccss = Ccss&"px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".lookmore {padding:5px 18px;}" & VbCrLf
	Ccss = Ccss&".lookmore a:link,.lookmore a:visited{color:#ff0000;}" & VbCrLf
	Ccss = Ccss&".red {color:#ff0000;font-weight:bold;margin:0 5px;}" & VbCrLf
	Ccss = Ccss&".artvote {width:537px;margin:10px auto;overflow:hidden;background:url(votetitle.jpg) top left no-repeat;}" & VbCrLf
	Ccss = Ccss&".artvote h5 {font:bold 18px ""Microsoft Yahei"",sans-serif;padding:6px 0 8px 0;text-align:center;}" & VbCrLf
	Ccss = Ccss&".artvote li {padding:5px 30px;}" & VbCrLf
	Ccss = Ccss&".artvote li .artsubmit {border:0;background:url(votesubmit.jpg) top left no-repeat;width:96px;height:32px;letter-spacing: 10px;font-size:14px;font-weight:bold;text-align:center;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*留言本首页*/" & VbCrLf
	Ccss = Ccss&".bbsborder {border:1px solid "&css("Color2")&";}" & VbCrLf
	Ccss = Ccss&".btitle {background:"&css("Color1")&";color:"&css("Color7")&";font-weight:bold;}" & VbCrLf
	Ccss = Ccss&".btitle a:link,.btitle a:visited,.btitle a:hover {color:"&css("Color4")&"}" & VbCrLf
	Ccss = Ccss&".bb {background:"&css("Color3")&";border-top:1px solid "&css("Color2")&";}" & VbCrLf
	Ccss = Ccss&".bb a{font-size:14px;}" & VbCrLf
	Ccss = Ccss&".user {color:#0066CC;}" & VbCrLf
	Ccss = Ccss&".date {color:#999;}" & VbCrLf
	Ccss = Ccss&".black {color:#ccc;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*显示留言*/" & VbCrLf
	Ccss = Ccss&".listtime {background:"&css("Color1")&";height:25px;border-bottom:1px solid "&css("Color3")&";text-align:left;color:"&css("Color4")&";padding-left:10px;}" & VbCrLf
	Ccss = Ccss&".listtime span {float:right;font-weight:bold;margin-right:15px;}" & VbCrLf
	Ccss = Ccss&".author {padding:10px 10px 5px 10px;margin:10px;font:bold 13px ""Microsoft Yahei"",sans-serif;text-align:left;border-bottom:1px dashed #ccc;}" & VbCrLf
	Ccss = Ccss&".author span {float:right;}" & VbCrLf
	Ccss = Ccss&".userface {width:100px;height:100px;line-height:100px;overflow:hidden;margin:0 auto;}" & VbCrLf
	Ccss = Ccss&".userface img {width:100px;height:100px;}" & VbCrLf
	Ccss = Ccss&".userip {margin-top:5px;color:#999;}" & VbCrLf
	Ccss = Ccss&".title {font-weight:bold;margin-bottom:10px;font-size:14px;}" & VbCrLf
	Ccss = Ccss&".bbscontent {background:"&css("Color3")&";font-size:14px;line-height:25px;text-align:left;padding:10px;vertical-align: top;}" & VbCrLf
	Ccss = Ccss&"#bbscontent {font-size:14px;word-break:break-all;width:745px; overflow:hidden; }" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".b4 {border:1px solid #ccc;width:350px;}" & VbCrLf
	Ccss = Ccss&".buttom {background:"&css("Color6")&";border:0;color:"&css("Color7")&";height:22px;}" & VbCrLf
	Ccss = Ccss&".dh span img {margin-right:10px;}" & VbCrLf
	Ccss = Ccss&".userinfo {text-align:left;margin:10px;}" & VbCrLf
	Ccss = Ccss&".userinfo li {border-bottom:1px dashed #ccc;line-height:25px;height:25px;}" & VbCrLf
	Ccss = Ccss&"#bbsqm {width:80%;margin-top:10px;padding-top:10px;background:url(signature_bg.gif) left top no-repeat;}" & VbCrLf
	Ccss = Ccss&"#bbsqm a:active {text:expression(target='_blank');}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".classdh {text-align:left;padding:10px;font-size:12px;font-weight:bold;}" & VbCrLf
	Ccss = Ccss&".classdh img{vertical-align:top}" & VbCrLf
	Ccss = Ccss&".classdh #yaobg {background:"&css("Color6")&";color:"&css("Color7")&";padding:2px 5px;}" & VbCrLf
	Ccss = Ccss&".classdh span {float:right;margin-top:-10px;}" & VbCrLf
	Ccss = Ccss&".textad a:link,.textad a:visited {color:#ff0000;}" & VbCrLf
	Ccss = Ccss&".textad a:hover {color:#0000ff;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#Artlist10,#Artlist10num {padding:2px 1px;}" & VbCrLf
	Ccss = Ccss&"#Artlist10 li {text-align:left;height:22px;line-height:22px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#Artlist10num li {text-align:left;height:22px;line-height:22px;padding-left:5px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#Artlist10 li span,#Artlist10num li span {float:right;}" & VbCrLf
	Ccss = Ccss&"#Artlist101 {padding:5px 0;}" & VbCrLf
	Ccss = Ccss&"#Artlist101 li {float:left;margin-left:3px;font-size:12px;width:248px;text-align:left;height:22px;line-height:22px;overflow:hidden;}" & VbCrLf
	Ccss = Ccss&"#Artlist101 li span {float:right;}" & VbCrLf
	Ccss = Ccss&"#indeximg {border-bottom:1px dashed #cccccc;margin-bottom:5px;height:110px;line-height:110px;}" & VbCrLf
	Ccss = Ccss&"#indeximg li {float:left;width:115px;text-align:center;height:100px;line-height:100px;padding:5px 0;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".nTableft {border:1px solid "&css("Color2")&";position: relative}" & VbCrLf
	Ccss = Ccss&".TabTitleleft {}" & VbCrLf
	Ccss = Ccss&".TabTitleleft li {float:left;line-height:200%;text-align:center;width:50%;border-bottom:1px solid "&css("Color2")&";cursor:pointer;}" & VbCrLf
	Ccss = Ccss&".TabTitleleft5 {background:#ffffff;}" & VbCrLf
	Ccss = Ccss&".TabTitleleft5 li {float:left;font-size:12px;color:"&css("Color4")&";font-weight:bold;line-height:200%;text-align:center;width:25%;border-bottom:1px solid "&css("Color2")&";cursor:pointer;}" & VbCrLf
	Ccss = Ccss&".TabTitleleft .active,.TabTitleleft5 .active{background:"&css("Color1")&";color:"&css("Color4")&";}" & VbCrLf
	Ccss = Ccss&".TabTitleleft .normal,.TabTitleleft5 .normal{font-weight:bold;color:"&css("Color5")&";background:"&css("Color3")&";}" & VbCrLf
	Ccss = Ccss&".TabContent3 {overflow:hidden;clear:both;padding-bottom:3px;}" & VbCrLf
	Ccss = Ccss&".nTableft td {text-align:left;height:22px;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&".indexvote h5 {margin:0 6px;font-size:14px;}" & VbCrLf
	Ccss = Ccss&".indexvote li {margin:2px;line-height:25px;}" & VbCrLf
	Ccss = Ccss&".indexvote .artsubmit {width:47px;height:21px;background:url(vote.gif) no-repeat;border:0;color:#fff;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*友情链接*/" & VbCrLf
	Ccss = Ccss&".black_overlay{display:none;position:absolute;top:0;left:0;width:100%;height:100%;background-color:black;z-index:1001;-moz-opacity:0.8;opacity:.80;filter:alpha(opacity=80);}" & VbCrLf
	Ccss = Ccss&".white_content{display:none;position:absolute;bottom:200px;left:0;width:400px;height:200px;padding:16px;border:16px solid "&css("Color2")&";background-color:white;z-index:1002;overflow:auto;}" & VbCrLf
	Ccss = Ccss&".white_content h5 span {float:right;}" & VbCrLf
	Ccss = Ccss&".white_content h5 {font:bold 16px ""Microsoft Yahei"",sans-serif;text-align:center;border-bottom:1px solid "&css("Color2")&";}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"#toptextad {border:1px solid "&css("Color2")&";width:950px;margin:0 auto 5px auto;text-align:left;padding:5px 0;height:20px;}" & VbCrLf
	Ccss = Ccss&"	#toptextad li{float:left;width:150px;text-align:center;padding-left:5px;line-height:20px;}" & VbCrLf
	Ccss = Ccss&".copylink {font-size:14px;margin:5px 0;} " & VbCrLf
	Ccss = Ccss&".copylink a{text-decoration:underline;}" & VbCrLf
	Ccss = Ccss&".laoynoi1 {font-size:14px; font-family:Arial; font-weight:bold;color:#ff0000; font-style:italic;}" & VbCrLf
	Ccss = Ccss&".laoynoi2 {font-size:14px; font-family:Arial; font-weight:bold;color:#79C04D; font-style:italic;}" & VbCrLf
	Ccss = Ccss&"" & VbCrLf
	Ccss = Ccss&"/*底部自定义页面*/" & VbCrLf
	Ccss = Ccss&".DiypageMenu {line-height:40px;}" & VbCrLf
	Ccss = Ccss&".DiypageMenu a{font-size:12px;color:"&css("Color7")&";}" & VbCrLf
	Ccss = Ccss&".topimg dl,#indeximg dl {" & VbCrLf
	Ccss = Ccss&"	overflow:hidden;margin:10px 0;" & VbCrLf
	Ccss = Ccss&"	padding:0px 10px;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&".topimg dl dt {" & VbCrLf
	Ccss = Ccss&"	float:left;" & VbCrLf
	Ccss = Ccss&"	width:75px;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&"#indeximg dl dt {" & VbCrLf
	Ccss = Ccss&"	float:left;" & VbCrLf
	Ccss = Ccss&"	width:105px;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&".topimg dl dd h2,#indeximg dl dd h2 {" & VbCrLf
	Ccss = Ccss&"	font-size:14px;" & VbCrLf
	Ccss = Ccss&"	height:22px;line-height:22px;" & VbCrLf
	Ccss = Ccss&"	overflow:hidden;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&".topimg dl dd div {" & VbCrLf
	Ccss = Ccss&"	line-height:20px;color:#666;height:40px;overflow:hidden;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&"#indeximg dl dd div {" & VbCrLf
	Ccss = Ccss&"	line-height:20px;color:#666;height:60px;overflow:hidden;" & VbCrLf
	Ccss = Ccss&"}" & VbCrLf
	Ccss = Ccss&".bdsharebuttonbox {width:270px;margin:0 auto;}" & VbCrLf
	Ccss = Ccss&"#a2{width:600px;margin:0 auto;}" & VbCrLf
	css.close
	set css=nothing
	Call CreateFile(Ccss,"../images/css"&cssid&".css")
end function
%>